# Generated by Django 4.0.1 on 2022-01-13 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0005_page_subpage_delete_note'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='subpage',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
