# Generated by Django 4.0.1 on 2022-01-15 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0007_alter_page_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
