# Generated by Django 4.0.1 on 2022-01-22 15:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0009_folder_remove_page_poster_delete_subpage_page_folder'),
    ]

    operations = [
        migrations.RenameField(
            model_name='folder',
            old_name='poster',
            new_name='owner',
        ),
    ]
