# Generated by Django 4.0.1 on 2022-01-23 16:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0012_alter_folder_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='pk_folder',
            field=models.CharField(blank=True, max_length=400, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='folder',
            name='title',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
