# Generated by Django 4.0.1 on 2022-01-23 18:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0013_folder_pk_folder_alter_folder_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chat_group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('administrator', models.ManyToManyField(related_name='my_group', to=settings.AUTH_USER_MODEL)),
                ('member', models.ManyToManyField(related_name='others_group', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Chat_message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(default='')),
                ('chat_group', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='chat_message', to='to_do_list.chat_group')),
                ('sender', models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='chat_message', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
