# Generated by Django 4.0.1 on 2022-01-24 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0014_chat_group_chat_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat_group',
            name='title',
            field=models.CharField(default='', max_length=200),
        ),
    ]
