# Generated by Django 4.0.1 on 2022-01-25 19:50

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0016_alter_chat_group_member'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chat_group',
            name='member',
            field=models.ManyToManyField(blank=True, related_name='others_group', to=settings.AUTH_USER_MODEL),
        ),
    ]
