# Generated by Django 4.0.1 on 2022-01-28 18:43

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0018_chat_group_people_read'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='folder',
            name='owner',
        ),
        migrations.AddField(
            model_name='folder',
            name='owner',
            field=models.ManyToManyField(related_name='folder', to=settings.AUTH_USER_MODEL),
        ),
    ]
