# Generated by Django 4.0.1 on 2022-01-29 16:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0019_remove_folder_owner_folder_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat_message',
            name='chat_group',
        ),
        migrations.RemoveField(
            model_name='chat_message',
            name='sender',
        ),
        migrations.DeleteModel(
            name='Chat_group',
        ),
        migrations.DeleteModel(
            name='Chat_message',
        ),
    ]
