# Generated by Django 4.0.1 on 2022-02-03 19:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0021_remove_folder_pk_folder'),
    ]

    operations = [
        migrations.AddField(
            model_name='folder',
            name='creator',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='myfolder', to=settings.AUTH_USER_MODEL),
        ),
    ]
