# Generated by Django 4.0.1 on 2022-02-13 18:48

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('to_do_list', '0022_folder_creator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='content',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
    ]
